[package]
name = "russdp"
version = "0.1.0"
authors = ["Andrew Osmond <aosmond@mozilla.com>"]

[dependencies]
httparse = "1.1.0"
hyper = "0.7.0"
log = "0.3"
net2 = "0.2.0"
time = "0.1"
xml-rs = "0.3.0"

